### ISSUE TITLE
大佬再加个图片预览,以防传错图片

### ISSUE THREAD

**Issue by insoxin** [yumusb/autoPicCdn#1]

**Comment by yumusb** [comment]
已经更新，感谢支持。

**Comment by insoxin** [comment]
> 已经更新，感谢支持。

我布置了最新的,然后提醒我
![image](https://user-images.githubusercontent.com/19371836/79826058-4ce79080-83cd-11ea-8e5c-8a93d6d05817.png)

![image](https://user-images.githubusercontent.com/19371836/79826153-8a4c1e00-83cd-11ea-9e79-d2de8776ee1d.png)

这不是数据相关的报错吧

**Comment by yumusb** [comment]
昨天更新忘记改readme了，已经写明、

**Comment by insoxin** [comment]
> 昨天更新忘记改readme了，已经写明、

数据库吗?数据库我是配置正确的

**Comment by yumusb** [comment]
> > 昨天更新忘记改readme了，已经写明、
> 
> 数据库吗?数据库我是配置正确的
> ![image](https://user-images.githubusercontent.com/19371836/79832740-a6a38700-83dc-11ea-9c81-9d809a836d8e.png)

TG找你了
