### ISSUE TITLE
都配置好了上产提示这个

### ISSUE THREAD

**Issue by amilys** [yumusb/autoPicCdn#12]
![image](https://user-images.githubusercontent.com/11211624/87872164-dfa5c480-c9e8-11ea-8222-944c48736259.png)

**Comment by yumusb** [comment]
这个问题，没充钱我不会解决


 
---原始邮件---
发件人: "Amily"<notifications@github.com&gt;
发送时间: 2020年7月19日 17:54:43
收件人: "yumusb/autoPicCdn"<autoPicCdn@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [yumusb/autoPicCdn] 都配置好了上产提示这个 (#12)

**Comment by amilys** [comment]
搞了半天是api.github.com被墙了
