### ISSUE TITLE
Jsdelivr屏蔽了大陆ip了

### ISSUE THREAD

**Issue by 8838** [yumusb/autoPicCdn#13]
请问能不能直接输出github的url，如果可以要怎么改动文件

**Comment by yumusb** [comment]
文件在你仓库，你问我链接。我缓缓打出一个？

**Comment by 8838** [comment]
思维方式不太一样？我觉得我说的很明白啦
那就再说清楚一点，现在Jsdelivr失效了，能不能不加Jsdelivr，直接输出github图片的url到图床？

**Comment by yumusb** [comment]
可以，但是我懒得改。确实需要的话，可以打钱羞辱我，我会改的。

**Comment by philipsc** [comment]
不要耸人听闻，只是屏蔽空请求头而已，从网站访问过去的还是能打开

**Comment by 8838** [comment]
> 不要耸人听闻，只是屏蔽空请求头而已，从网站访问过去的还是能打开

意思就是对于图床来说没有任何影响，只是不能单独请求url？

**Comment by yumusb** [comment]
各位可以把心放到肚子里了。
