### ISSUE TITLE
Failed to fetch version info for Nicotinamide/images.

### ISSUE THREAD

**Issue by Nicotinamide** [yumusb/autoPicCdn#15]
有些图片没问题，有些图片会出现Failed to fetch version info for Nicotinamide/images.错误，图片刚上传没有问题，但是过一段时间出现这个错误

**Comment by silenvps20** [comment]
遇到同样错误

**Comment by yumusb** [comment]
目前已经有解决方案。但是有效性未知。可以先到 chuibi.cn 登录账号进行试验 。 如果有效会更新到这里。

**Comment by silenvps20** [comment]
@yumusb 测试过 可以打开

**Comment by yumusb** [comment]
> @yumusb 测试过 可以打开

我的意思是多传点图片测试下会不会出现 Failed to fetch version info for Nicotinamide/images.

**Comment by silenvps20** [comment]
@yumusb 我传了大概10张 都能打开
