### ISSUE TITLE
返回的链接无法访问

### ISSUE THREAD

**Issue by xingjiahui** [yumusb/autoPicCdn#19]
1. 问题：返回的链接无法访问
- 返回链接：https://cdn.jsdelivr.net/gh/zghya/PicGotuchuang@latest/2020/10/25/2dd2b9d2d702f7177714d0bd09d8725a.png
- 浏览器访问：
![](https://cdn.jsdelivr.net/gh/xingjiahui/CDN@latest/2020/10/25/66f5fbf335af7c37edd65246b58cb375.png)

2. 解决方法：
- 编辑 up.php-> 搜索 @latest 将 latest 修改为 main
![](https://cdn.jsdelivr.net/gh/xingjiahui/CDN@latest/2020/10/18/cc56b7fd3cf49e187dd3fd24b82485fb.png)
- 修改后返回链接：https://cdn.jsdelivr.net/gh/zghya/PicGotuchuang@main/2020/10/25/2dd2b9d2d702f7177714d0bd09d8725a.png

3. 注意：
- 旧仓库（主分支为master）时不会出现这种情况
- 新建的仓库（主分支为main）才会出现这种情况

**Comment by yumusb** [comment]
// load any GitHub release, commit, or branch

// note: we recommend using npm for projects that support it

之前一直在chuibi.cn测试使用commit的sha值方式调用。并没有推送上来，既然现在latest不能用了，那就直接推上来吧。
