### ISSUE TITLE
是否可以开放后端接口

### ISSUE THREAD

**Issue by orange2008** [yumusb/autoPicCdn#20]
我是一个程序员，我会想要重新自己写一个前端，直接用python的requests进行POST请求这个文件并处理返回的JSON，但我不知道上传到up.php的name是什么，相当于html里form的input name是什么。

**Comment by yumusb** [comment]
https://github.com/yumusb/autoPicCdn/blob/7cbcdbb4bdac90429f3f0eff4fbc2b0b84183644/up.php#L155
参数名 pic
