### ISSUE TITLE
PicGo上传后返回链接

### ISSUE THREAD

**Issue by nangongxiaoxin** [yumusb/autoPicCdn#25]
大哥，使用PicGo上传后返回链接的链接都是形如{"code":"success","data":{"url":"https:\/\/cdn.jsdelivr.net\/gh\/nangongxiaoxin\/img@fcdc43c398c2f0804f1092d6815e60cf5ea59eb8\/2021\/02\/19\/091beb3de43f7782355099c21a71208f.png","filemd5":"07a1f426de4c7d36d7981c486d55c705"}}这种，该调整哪个位置才能变成像https://cdn.jsdelivr.net/gh/nangongxiaoxin/img@fcdc43c398c2f0804f1092d6815e60cf5ea59eb8/2021/02/19/091beb3de43f7782355099c21a71208f.png   这样的正常链接

**Comment by mos1128** [comment]
返回的是json数据，解析即可

**Comment by nangongxiaoxin** [comment]
ok.已经解决，感谢

**Comment by xiangshu233** [comment]
请问如何解决的，我也不知道为什么出现这个问题
