### ISSUE TITLE
要是能增加一个链接远程数据库的功能就OK了

### ISSUE THREAD

**Issue by deary** [yumusb/autoPicCdn#28]
要是能增加一个链接远程数据库的功能就OK了

有的PHP空间不提供数据库

**Comment by yumusb** [comment]
你把 localhost 改成你自己的远程地址 不就成了？

**Comment by deary** [comment]
> 你把localhost改成你自己的远程地址不就变成了？

刚刚才想起来，准备来删评论的 。不好意思啊
