### ISSUE TITLE
大佬可以加一个简单的管理页面吗

### ISSUE THREAD

**Issue by hietsusama** [yumusb/autoPicCdn#3]
把图片存进去
后面重复利用图片的话直接在后台提取。不用二次上传了
不用分什么游客之类的，都是自用的，设置个简单的密码就可以了。

**Comment by yumusb** [comment]
这个简单，你不公开不就行了。现在已经有文件记录功能了，相同md5的不会二次上传。

**Comment by Insightfy** [comment]
数据库找到了。
我的意思是说可不可以直接加一个管理页面上，然后比如我很早之前的图就想直接找到他的链接，
或者一次性的图 用完过几天想删除。Github上来来回回删除也不方便的亚子
看到数据库也能管理 
但是有时候不太方便登录主机，不知道这个功能方便实现吗？
感谢大佬无私奉献 谢谢

**Comment by yumusb** [comment]
删除毫无意义。文件会缓存到jsd的服务器，就算删除掉github的文件，URL链接并不会失效（同时也意味着更新文件也不会更新）。展示页面可以考虑。

**Comment by Insightfy** [comment]
jsd没关系 反正只要本地删了这个链接就没人能找到。
如果g提供github仓库删除接口
和历史图片展示页面那就太感谢了。
还是非常感谢大佬的

**Comment by yumusb** [comment]
（疯狂暗示：
![](https://cdn.jsdelivr.net/gh/pic-cdn/cdn1@latest/2020/04/21/26c313f7ac35204a9f7e3ee5db91736d.png)

**Comment by Insightfy** [comment]
star fork follow 
一键三连
👌

**Comment by philipsc** [comment]
白嫖的多了  会不会炸啊

**Comment by yumusb** [comment]
JsD对Github仓库的单分支有50MB限额。
Gitee限制单文件1M以上的文件需要访客登录方能访问。

**Comment by yumusb** [comment]
> 白嫖的多了 会不会炸啊

JsD对Github仓库的单分支有50MB限额。
Gitee限制单文件1M以上的文件需要访客登录方能访问。
