### ISSUE TITLE
https://chuibi.cn/ 这个链接打不开了

### ISSUE THREAD

**Issue by yoke0104x** [yumusb/autoPicCdn#38]
https://chuibi.cn/ 这个链接打不开了

**Comment by yumusb** [comment]
跑路了

**Comment by yoke0104x** [comment]
？？？跑路了？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月21日 17:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [yumusb/autoPicCdn] https://chuibi.cn/ 这个链接打不开了 (Issue #38) |

Closed #38 as completed.
