### ISSUE TITLE
需要手动配置数据库吗

### ISSUE THREAD

**Issue by o1f** [yumusb/autoPicCdn#4]
@latest最好换成@master,要不然有时候报错
Package size exceeded the configured limit of 50 MB

**Comment by yumusb** [comment]
就是master报错我才换成lastest的= =、

**Comment by o1f** [comment]
lastes 是最新的包, 如果发布的仓库版本>50m就会报错 

master 是按照分支拉取的 .

按理来说 master, 更稳一些...
