### ISSUE TITLE
提示“上传失败，我们会尽快修复”

### ISSUE THREAD

**Issue by jvfan** [yumusb/autoPicCdn#6]
我将 autoPicCdn 放在了phpEnv建立的本地环境下，配置 MySQL 和 up.php 后，拖入图片没有上传成功，在 tokens 管理页显示 token 没有被使用过。

而PicGo可以上传成功。

**Comment by jvfan** [comment]
失败图示：
![](https://gitee.com//mypic/Images/raw/master/img/20200516145010.png)

**Comment by yumusb** [comment]
大家都不能用代表程序bug，别人能用你不能用代表你没设置好。你可以邮箱私发我配置，我看下。

**Comment by jvfan** [comment]
> 大家都不能用代表程序bug，别人能用你不能用代表你没设置好。你可以邮箱私发我配置，我看下。

大佬，已发送到你的邮箱： yumusb@foxmail.com 上了，麻烦帮我看看

**Comment by jvfan** [comment]
感觉大佬解答，需要 curl 工具的支持。已关闭此issue
