### ISSUE TITLE
按照要求填写了up.php，但是无效。

### ISSUE THREAD

**Issue by Ebeo-Yvnjiang** [yumusb/autoPicCdn#8]
如题。

**Comment by Ebeo-Yvnjiang** [comment]
https://github.com/Ebeo-Yvnjiang/autoPicCdn  
https://github.com/Ebeo-Yvnjiang/SiyuanAK

**Comment by Ebeo-Yvnjiang** [comment]
显示“接口出现异常”，页面地址在 https://bed.billy2007.tk 。

**Comment by yumusb** [comment]
数据库没有配置，请不要公开你的个人token信息在github上。 不会配置的话 用 https://chuibi.cn/ 足以、

**Comment by Ebeo-Yvnjiang** [comment]
如何配置数据库？
