### ISSUE TITLE
更新了7月7号的up.php无法上传文件

### ISSUE THREAD

**Issue by philipsc** [yumusb/autoPicCdn#9]
如题所示，上传后提示如下面截图
![](https://cdn.jsdelivr.net/gh/pic-cdn/cdn1@latest/2020/07/08/9e6e9b91d2735a00019a98c5f73df354.png)

**Comment by yumusb** [comment]
//必选项
define("TYPE","GITHUB");//选择github
//define("TYPE","GITEE");//选择gitee，如果使用gitee，需要手动建立master分支，可以看这里 https://gitee.com/help/articles/4122

**Comment by philipsc** [comment]
> //必选项
> define("TYPE","GITHUB");//选择github
> //define("TYPE","GITEE");//选择gitee，如果使用gitee，需要手动建立master分支，可以看这里 https://gitee.com/help/articles/4122

必选项默认的就是GITHUB我并没有做更改

**Comment by yumusb** [comment]
> > //必选项
> > define("TYPE","GITHUB");//选择github
> > //define("TYPE","GITEE");//选择gitee，如果使用gitee，需要手动建立master分支，可以看这里 https://gitee.com/help/articles/4122
> 
> 必选项默认的就是GITHUB我并没有做更改

已修复，更改的内容忘记做测试了。现在下载就可以了。

**Comment by philipsc** [comment]
> > > //必选项
> > > define("TYPE","GITHUB");//选择github
> > > //define("TYPE","GITEE");//选择gitee，如果使用gitee，需要手动建立master分支，可以看这里 https://gitee.com/help/articles/4122
> > 
> > 
> > 必选项默认的就是GITHUB我并没有做更改
> 
> 已修复，更改的内容忘记做测试了。现在下载就可以了。

好了
